<div id="content" class="content page-error" role="main">
	<div class="wrapper content-container page-container">
		<div class="flexbox">
            <div class="one-half">
                <div class="error-image">
                    <img class="aligncenter" src="<?php echo $image_src; ?>" alt="" role="presentation">
                </div>
            </div>
			<div id="error-content" class="one-half">
				<div class="page-header">
					<h1 class="entry-title"><?php echo $title; ?></h1> <!-- entry-title -->
				</div> <!-- .page-header -->
				<div class="page-content">
                    <?php echo $content; ?>
				</div> <!-- .page-content -->
			</div> <!-- .page -->
		</div> <!-- .main -->
	</div> <!-- .wrapper -->
</div> <!-- #content .content -->
