<div id="content" class="content main" role="main">
	<div class="wrapper">
			<div id="page-<?php echo $page_id; ?>" <?php echo $page_classes; ?>>
				<div class="flexbox">
                    <div class="header-image one-half">
                        <img class="aligncenter" alt="" src="<?php echo $header_image_url; ?>">
                    </div>
                    <div class="page-content one-half">
	                    <?php echo $content; ?>
	                    <?php echo $edit_link; ?>
                    </div>
				</div> <!-- .page-content -->
			</div> <!-- .page -->
	</div> <!-- .wrapper -->
    <div class="">

    </div>
    <div class="social-bar-front clear-all">
        <div class="wrapper">
            <div class="social-bar-front-widgets">
	            <?php echo $social_sidebar; ?>
            </div> <!-- .social-bar-front-widgets -->
        </div> <!-- .wrapper -->
    </div> <!-- .footer-front -->
    <div class="category_preview">
        <?php echo $categories_preview; ?>
    </div>
</div> <!-- #content .content -->