<div id="content" class="content main" role="main">
	<div class="wrapper">
			<div id="page-<?php echo $page_id; ?>" <?php echo $page_classes; ?>>
				<div class="flexbox">
                    <div class="header-image one-half">
	                    <?php echo $header_image; ?>
                    </div>
                    <div class="one-half">
                        <div class="page-content">
	                        <?php echo $content; ?>
	                        <?php echo $edit_link; ?>
                        </div>
                    </div>
				</div> <!-- .page-content -->
			</div> <!-- .page -->
	</div> <!-- .wrapper -->
    <?php if ($social_banner) { ?>
        <div class="social-bar-front clear-all">
            <div class="wrapper">
                <div class="social-bar-front-widgets">
                    <?php echo $social_banner; ?>
                </div> <!-- .social-bar-front-widgets -->
            </div> <!-- .wrapper -->
        </div> <!-- .social-bar-front -->
    <?php } ?>
    <div class="category_preview">
        <?php echo $categories_preview; ?>
    </div> <!-- .category_preview -->
    <?php if ($embed_banner) { ?>
        <div class="embed-bar-front clear-all">
            <div class="wrapper">
                <div class="embed-bar-front-widgets">
                    <?php echo $embed_banner; ?>
                </div> <!-- .embed-bar-front-widgets -->
            </div> <!-- .wrapper -->
        </div> <!-- .embed-bar-front -->
    <?php } ?>
</div> <!-- #content .content -->
