	<meta name="keywords" content="<?php echo $keywords; ?>">
	<meta name="description" content="<?php echo $description; ?>">

	<meta name="author" content="<?php echo $author; ?>">
	<meta name="copyright" content="<?php echo $copyright; ?>">
	<link rel="author" href="<?php echo $humans_file; ?>">
	<meta charset="<?php echo $charset; ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!--[if IE]>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<![endif]-->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo $google_font_stylesheet; ?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $normalize_stylesheet; ?>">
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $theme_stylesheet; ?>">