<a class="screen-reader-text skip-link" href="#content" title="<?php echo $skip_to_content_text; ?>">
    <?php echo $skip_to_content_text; ?>
</a>
<div class="header" role="banner">
	<div class="wrapper">
		<div class="flexbox">
			<div class="site-header">
				<?php echo $logo; ?>
				<div class="site-details">
					<div class="site-title">
						<?php echo $name; ?>
					</div>
					<div class="site-tagline">
						<?php echo $tagline; ?>
					</div>
				</div>
			</div> <!-- .header -->
			<div class="nav" role="navigation" aria-label="<?php echo $aria_label; ?>">
				<?php echo $nav_menu_list; ?>
			</div> <!-- .navigation -->
		</div> <!-- .flexbox -->
	</div> <!-- .wrapper -->
</div> <!-- .header -->
