<div id="content" class="content">
	<div class="wrapper content-container page-container tile">
        <div class="main">
            <div id="page-<?php echo $page_id; ?>" <?php echo $page_classes; ?>>
                <div class="page-header clear-all">
                    <h1 class="entry-title"><?php echo $title; ?></h1> <!-- entry-title -->
                </div> <!-- .page-header -->
                <div class="page-content clear-all">
                    <?php echo $content; ?>
                </div> <!-- .page-content -->
	            <?php echo $edit_link; ?>
            </div> <!-- .page -->
        </div> <!-- .main -->
	</div> <!-- .wrapper -->
</div> <!-- #content .content -->