<div class="column <?php echo $column_class; ?>" role="treeitem">
	<div class="post-preview-block">
		<div class="preview-preview-thumb text-aligncenter">
            <a rel="bookmark" href="<?php echo $url; ?>">
                <span class="screen-reader-text"><?php echo $thumbnail_alt_text; ?></span>
	            <?php echo $thumbnail; ?>
            </a>
		</div>
		<h3 class="post-preview-title">
            <a rel="bookmark" href="<?php echo $url; ?>">
                <?php echo $title; ?>
            </a>
        </h3>
		<div class="post-preview-excerpt">
			<p>
				<?php echo $excerpt; ?>
			</p>
		</div>
		<?php echo $read_more_link; ?>
	</div>
</div>
