<div id="content" class="content">
	<div class="wrapper content-container page-content-container">
        <div class="flexbox">
            <div class="two-thirds">
                <div class="main" role="main">
                    <h1 class="post-list-title"><?php echo $title; ?></h1> <!-- .page-title -->
                    <div class="page-content post-list clear-all">
                        <?php echo $pagination; ?>
                        <?php echo $post_list; ?>
                        <?php echo $pagination; ?>
                    </div> <!-- .page-content -->
                </div> <!-- .main -->
            </div>
            <div class="aside sidebar one-third">
                <?php echo $sidebar; ?>
            </div> <!-- .sidebar-widgets -->
        </div>
	</div> <!-- .wrapper -->
</div> <!-- #content .content -->