<div class="front-page-category">
    <div class="wrapper">
        <h2 class="category-title"><?php echo $name; ?></h2>
        <div class="category-description">
            <p>
			    <?php echo $description; ?>
            </p>
        </div> <!-- .category-description -->
        <div class="category-list flexbox" role="group">
		    <?php echo $post_previews; ?>
        </div> <!-- .category-list -->
        <div class="category-link">
            <a class="button-link gold-button" href="<?php echo $url; ?>">
		        <?php echo $url_text; ?>
            </a>
        </div> <!-- .category-link -->
    </div> <!-- .wrapper -->
</div> <!-- .front-page-category -->
