<p>
	<label for="<?php echo $title_id; ?>"><?php echo $title_label; ?></label>
	<input class="widefat" id="<?php echo $title_id; ?>" name="<?php echo $title_name; ?>"
	       type="text" value="<?php echo $title_value; ?>" />
</p>
<p>
	<?php echo $instructions; ?>
</p>
<p>
	<label for="<?php echo $facebook_id; ?>"><?php echo $facebook_label; ?></label>
	<input class="widefat" id="<?php echo $facebook_id; ?>" name="<?php echo $facebook_name; ?>"
	       type="text" value="<?php echo $facebook_value; ?>" />
</p>
<p>
	<label for="<?php echo $twitter_id; ?>"><?php echo $twitter_label; ?></label>
	<input class="widefat" id="<?php echo $twitter_id; ?>" name="<?php echo $twitter_name; ?>"
	       type="text" value="<?php echo $twitter_value; ?>" />
</p>
<p>
	<label for="<?php echo $pinterest_id; ?>"><?php echo $pinterest_label; ?></label>
	<input class="widefat" id="<?php echo $pinterest_id; ?>" name="<?php echo $pinterest_name; ?>"
	       type="text" value="<?php echo $pinterest_value; ?>" />
</p>
<p>
	<label for="<?php echo $linkedin_id; ?>"><?php echo $linkedin_label; ?></label>
	<input class="widefat" id="<?php echo $linkedin_id; ?>" name="<?php echo $linkedin_name; ?>"
	       type="text" value="<?php echo $linkedin_value; ?>" />
</p>
<p>
	<label for="<?php echo $youtube_id; ?>"><?php echo $youtube_label; ?></label>
	<input class="widefat" id="<?php echo $youtube_id; ?>" name="<?php echo $youtube_name; ?>"
	       type="text" value="<?php echo $youtube_value; ?>" />
</p>
<p>
	<label for="<?php echo $github_id; ?>"><?php echo $github_label; ?></label>
	<input class="widefat" id="<?php echo $github_id; ?>" name="<?php echo $github_name; ?>"
	       type="text" value="<?php echo $github_value; ?>" />
</p>
<p>
	<label for="<?php echo $tumblr_id; ?>"><?php echo $tumblr_label; ?></label>
	<input class="widefat" id="<?php echo $tumblr_id; ?>" name="<?php echo $tumblr_name; ?>"
	       type="text" value="<?php echo $tumblr_value; ?>" />
</p>