<div class="post-comments clear-all">
    <div id="comments" class="comments-area">
        <h2 class="comments-title">
            <?php echo $title; ?>
        </h2> <!-- .comments-title -->
	    <?php echo $form; ?>
        <?php echo $navigation; ?>
        <ol class="comment-list">
            <?php echo $list; ?>
        </ol> <!-- .comments-list -->
        <?php echo $navigation; ?>
    </div> <!-- .comments-area -->
</div> <!-- .post-comments -->